include: package:flutter_lints/flutter.yaml

plugins:
  many_lints:
    version: ^0.4.0
    diagnostics:
      avoid_bloc_public_methods: false
      avoid_passing_bloc_to_bloc: false
      avoid_passing_build_context_to_blocs: false
      use_bloc_suffix: false

      dispose_provided_instances: false

analyzer:
  errors:
    missing_return: error
    dead_code: warning
  exclude:
    - "**/*.g.dart"        
    - "**/*.freezed.dart"  
    - "lib/generated/**"  

lints:
  rules:
    - always_use_package_imports
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_locals
    - sized_box_for_whitespace
    - use_super_parameters